export const HOME_FILTER_MEASUREMENTS='measurements'
export const HOME_FILTER_COOKING_METHOD='cookingMethod'
export const HOME_FILTER_INGREDIENTS='ingredients'
export const HOME_FILTER_RECIPE='recipe'
export const HOME_FILTER_ALL='all'